### ISSUE TITLE
Internal deployments for Web UI?

### ISSUE THREAD

**Issue by geekdave** [GoogleChrome/big-rig#15]
We're interested in exploring big-rig as an internal tool behind our firewall, for testing dev & QA environments that are not exposed to the public internet.  

Any plans to support deploying the Web UI on internal company-owned servers, instead of Google App engine (which I'm not very familiar with, but I assume locks you into their public cloud?)

Thanks!

**Comment by paullewis** [comment]
You can use the Google App Engine SDK / Launcher and run that on a machine. That would let you run it on your own box. Meanwhile, I'm going to build a node-based version of the web app for folks who want to run internally without additional requirements.
