### ISSUE TITLE
Could you explain a bit about how data is persisted?

### ISSUE THREAD

**Issue by okor** [GoogleChrome/big-rig#17]
Are you just saving JSON to disk?

ty

**Comment by paullewis** [comment]
It's all [ndb requests in GAE](https://cloud.google.com/appengine/docs/python/ndb/). I'm not sure how it's backed, though, but you can [see the models in the source](https://github.com/GoogleChrome/big-rig/blob/master/app/src/bigrig/models.py). Once Big Rig has processed the data it stores the result in the store.
