### ISSUE TITLE
[Documentation] big-rig UI Installation to Google App Engine unclear

### ISSUE THREAD

**Issue by KempfCreative** [GoogleChrome/big-rig#19]
Perhaps this is due to my lack of experience in Google App Engine, but the installation instructions for the UI portion of this project are unclear. (https://github.com/GoogleChrome/big-rig/tree/master/app#installation).
Specifically, step 5, which somehow links the big-rig repo to Google App Engine, is where I am stuck. There are no directions as to how to link the dist/ folder to the Google App Engine, whether that happens via command line, via the Google App Engine front-end UI, or otherwise.

If this is simply a case of "read all the documentation & watch all the videos on GAE, then you will understand", then that is a fair point, but I feel that some breadcrumbs to get people started would be helpful.

**Comment by robdodson** [comment]
Yeah that could maybe be cleared up a bit more in the docs for anyone new to GAE.

@KempfCreative if you open the app engine launcher, there's a little plus button in the bottom left corner

<img width="669" alt="screen shot 2015-11-21 at 8 10 39 pm" src="https://cloud.githubusercontent.com/assets/1066253/11322032/ff45b606-908b-11e5-8cb6-97f1acb69861.png">

Click on that, and it'll open a dialog where you can add your `dist` directory

**Comment by KempfCreative** [comment]
@robdodson, the main issue I am having is in getting that app screen above to show up. In the directions listed, running gulp should probably also have some sort of app startup script which would start the GoogleAppEngineLauncher, so that the next step; adding the /dist/ folder can be accomplished. However, all gulp is doing is generating the /dist/ folder.

Is there a GoogleAppEngine command I am missing to get the screen above to show up?

**Comment by robdodson** [comment]
@KempfCreative the app engine launcher is a regular program that gets installed when you install the [Python SDK](https://cloud.google.com/appengine/downloads?hl=en). If you're on a mac you can find it using Spotlight (it should be in your Applications directory). If you're on Windows/Linux I'm not quite sure where it lives :P

**Comment by KempfCreative** [comment]
@robdodson: Based on your help, I have this working. Here are the steps I had trouble following, FYI:
-  Step 1: Download the Google Cloud SDK:
  -  The link in this repo takes you to a page that will lead you to installing the gcloud CLI, which AFAIK, will not help any users in getting this project running. (This could possibly be a pre-req in the Python SDK, but I am not sure).
-  Step 2: Clone the repo:
  -  This didn't throw me at all, but based on the context of step 1, some people could assume that the directions are for gcloud, not for this repo. Changing the wording to _clone this repo_, would probably alleviate any confusion.
-  Step 5: Add the /dist folder as an existing project:
  -  Personally, due to my experience with Google App Engine, there was no way I was going to figure out to download the Python SDK to get this to run. Directions as to download this app should probably replace Step 1 (if the gcloud init is not a pre-req).
-  Big-rig login:
  -  This app will only accept the default email address, and will throw errors if any others are used. I am sure this is quite obvious in the Python code, but calling it out wouldn't be a terrible idea IMO.

Everything else is looking good. Great work and thanks for the help!
