### ISSUE TITLE
Remove --file

### ISSUE THREAD

**Issue by jillesme** [GoogleChrome/big-rig#23]
I have been using bigrig a lot lately. I have created a custom alias (`alias br="bigrig --file"`) because I got tired of typing --file all the time when all I do is pretty print a file.

What is your opinion on dropping the whole --file argument and just assume the first argument is the file path? Most cli tools have that (for example mkdir: it's `mkdir [folder]`, not `mkdir --directory [folder]`)

Let me know what you think!

**Comment by paullewis** [comment]
Yeah I'd be cool with this. I could try and default it so if we get no --file param but a path that we use that. Seems good. Can you file it against github.com/googlechrome/node-big-rig/issues so I can track it there?

**Comment by jillesme** [comment]
Done!
