### ISSUE TITLE
Name too close to a particular game

### ISSUE THREAD

**Issue by taisel** [GoogleChrome/big-rig#36]
https://en.wikipedia.org/wiki/Big_Rigs:_Over_the_Road_Racing

Yeah, I'm bringing it up because that particular game was notoriously infamous for particularly bad programming reasons... When I first heard "big-rig" I thought it was the game, not a Google project.

**Comment by paullewis** [comment]
The issue with the game was that, according to every review, it was diabolically bad, right? This feels on-brand for something I've built. #tongueincheek

Thanks for the heads up, though, I'll have a look.

**Comment by PaulKinlan** [comment]
I think for a niche of games players this might conjure up an association, but I know that game well and I didn't think about it when this name was chosen.  I don't think it is an issue really.
