### ISSUE TITLE
Web app says "Hello World!"

### ISSUE THREAD

**Issue by zzarcon** [GoogleChrome/big-rig#38]
I'm trying to make the web app working but for some reason i just see _Hello world!_ in the screen when entering in **http://localhost:8080/**. Later if I try to enter in **http://localhost:8080/help/getting-started/** it returns a 404.

![](http://new.tinygrab.com/e14c28c920af365f485e49ecfca8834dd51ae8fb05.png)

![](http://new.tinygrab.com/e14c28c9208e36610ca34b24a531eaa14528d0e08e.png)

Probably I'm missing something obvious but I have no idea of what, can someone help me? thanks!

**Comment by zzarcon** [comment]
@aerotwist any idea?

**Comment by zzarcon** [comment]
@paullewis any idea?

**Comment by paullewis** [comment]
Are you building and adding it as an existing project? (There's a distinction between creating a new one and adding an existing one in the launcher.)

**Comment by zzarcon** [comment]
That was the issue, working fine now.

Thanks @paullewis
