### ISSUE TITLE
Alternatives

### ISSUE THREAD

**Issue by madskonradsen** [GoogleChrome/big-rig#42]
Just stumbled upon this project and it's just what I'm looking for! It looks amazing! But looking at the "Pulse" of this project, it looks like it's unmaintained :( Have development moved to another place? In case the project is completely abandoned, do similar alternatives exist?

Thanks in advance!

**Comment by yosiat** [comment]
@madskonradsen I think lighthouse replaces big-rig

https://github.com/GoogleChrome/lighthouse
https://www.youtube.com/watch?v=d98CAgQNeaM

**Comment by madskonradsen** [comment]
Yeah, it looks like it's the best bet. Unfortunately it doesn't have the same focus on Paint/Layout-time over time which is nice in a CI environment, but thanks! :) Think I'll just close this up then
